/**
 * @file ast_list.h
 * @author your name (you@domain.com)
 * @brief Protects list of AST generated by list.h from redeclaration
 */
#pragma once

#ifndef _AST_LIST_H_
#define _AST_LIST_H_

#include "ast.h"
#include "list.h"

DECLARE_LIST(ast, struct AST*)

#endif